# Site Settings
title: Dr. Ted Leandro de Almeida - Researcher and professor at INPE/Brazil
url: 'https://monolipo.github.io'
description: Official academic website of Dr. Leandro de Almeida, also know as Ted Leandro de Almeida, astrophysicist, researcher and professor at INPE, Brazil.
theme_skin: custom
chrome_mobile_color: '#800020'

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
